[workspace]
resolver = "3"

members = [
    "kernel", "xtask"
]

exclude = [
    "tools/config",
]

default-members = ["kernel"]

[profile.dev]
panic = "abort"
strip = false
opt-level = "z"

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true

